export const authAction = {
  USER_SIGN_IN_PROGRESS: 'USER_SIGN_IN_PROGRESS',
  USER_SIGNED_IN: 'USER_SIGNED_IN',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_OUT_ERROR: 'SIGN_OUT_ERROR',
}